# Generated by Django 2.1.7 on 2019-03-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMember',
            fields=[
                ('uid', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='/static/ogresite/entity/av_default.jpg', upload_to='static/ogresite/forum')),
                ('signature', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_member_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('uid', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postforum_ForumMember', to='forum.ForumMember')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadForum',
            fields=[
                ('uid', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('category', models.PositiveIntegerField(choices=[(1, 'Accueil'), (2, "Forum de l'ogre"), (3, 'Aventures'), (4, 'Divers')])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threadforum_ForumMember', to='forum.ForumMember')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadLastVisit',
            fields=[
                ('uid', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_thread_last_visit', to='forum.ForumMember')),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_thread_last_visit', to='forum.ThreadForum')),
            ],
        ),
        migrations.AddField(
            model_name='postforum',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postforum_threadForum', to='forum.ThreadForum'),
        ),
    ]
