# Generated by Django 2.1.7 on 2019-03-24 08:06

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforum',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
