# Generated by Django 2.1.7 on 2019-06-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190331_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('uid', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rank_visibility', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='forummember',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threadforum',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_category', to='forum.ForumCategory'),
        ),
    ]
