# Generated by Django 2.1.7 on 2019-08-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190617_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforum',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postforum_threadForum', to='forum.ThreadForum'),
        ),
        migrations.AlterField(
            model_name='threadlastvisit',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_thread_last_visit', to='forum.ForumMember'),
        ),
        migrations.AlterField(
            model_name='threadlastvisit',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_thread_last_visit', to='forum.ThreadForum'),
        ),
    ]
